### ISSUE TITLE
Deflection/Enhancement/Natural Armor/Resistance Bonuses Stuck at 1

### ISSUE THREAD

**Issue by Marros56** [WittleWolfie/AutomaticBonusProgression#1]
Mod used: Toybox, TTCore, Mod Menu

Created a Midnight Isles character, gave them a couple magic items to test and alternated between giving them regular and mythic levels with toybox. All of the bonuses were applied when first unlocked but never increased as I leveled up. The level up menu and the Character Abilities screen showed attunment/toughening/etc. at the proper values, checking the attack, AC, and save breakdowns never showed anything past 1 for each.

**Comment by Marros56** [comment]
[GameLogFull.txt](https://github.com/WittleWolfie/AutomaticBonusProgression/files/12071921/GameLogFull.txt)
attempted to recreate this issue and grabbed the log. on the player side all I did was load a new midnight Isles save with the pre built fighter. loaded into the port, immediately leveled to him to 5 with toybox, gave him a mythic level, leveled him to 9, gave him another mythic level, leveled him to 12, then gave him 3rd mythic level with the angel path, recruited a second party member, did not level them up, talked to the helmsman to start the dlc, got to the first Island, saved and closed the game.

**Comment by Marros56** [comment]
[Player.log](https://github.com/WittleWolfie/AutomaticBonusProgression/files/12071969/Player.log)
Player log as well

**Comment by WittleWolfie** [comment]
Looks like this is an issue w/ ranks. I've got a fix ready, though it will require respeccing unfortunately.
