### ISSUE TITLE
Legend Path gets scaling Legendary Gifts instead of 1 per level

### ISSUE THREAD

**Issue by Variseraphim** [WittleWolfie/AutomaticBonusProgression#11]
As title says, at 21st level, you get 1 Legendary Gift, but at 22nd and 23rd level, you get 2, at 24th and 25th you get 3, and so on and so forth. At 33rd level, I was getting 6 Legendary Gifts and had practically run out of options, unable to proceed. Luckily, I had ToyBox installed and could manually remove the excess gifts and am doing so each level.

**Comment by WittleWolfie** [comment]
Thanks for the report, fixed!
