### ISSUE TITLE
Enchantment problem

### ISSUE THREAD

**Issue by xzszlkd** [WittleWolfie/AutomaticBonusProgression#12]
Sometimes it will cause the main weapon's enchantment all unavailable what if the secondary weapon does not have this problem

**Comment by xzszlkd** [comment]
I've got a whiteboard weapon in my first weapon position and then I've got a multi-enchantment item in the second equipment bar that cuts back to the main weapon and will never be enchanted

**Comment by xzszlkd** [comment]
My whiteboard weapon number one is enchanted and then the multi-enchanted weapon number two is cut back to number one and the main weapon will never be enchanted

**Comment by xzszlkd** [comment]
My Whiteboard weapon number one is enchanted and then the multi-enchanted weapon number two will never be enchanted when I switch back to the main weapon number one

**Comment by WittleWolfie** [comment]
Can you provide a save & list of mods?

Also can you clarify the steps? Based on your comments I assume this is about switching weapon sets?

**Comment by xzszlkd** [comment]
![Uploading QQ图片20230903191354.png…]()

**Comment by xzszlkd** [comment]
![QQ图片20230903191354](https://github.com/WittleWolfie/AutomaticBonusProgression/assets/143374051/caf995e0-db28-4fdf-80cc-150e821c752c)

**Comment by WittleWolfie** [comment]
I have not been able to reproduce any problems. Here is how the mod works with weapon sets:

- When you change your active weapons, enchantments are removed from your current set and applied to the new set
- Enchantment requirements are checked before applying to the new set

This can result in enchantments not applying to the new set. For example, if you have a sword (Melee, Slashing) equipped and the Culling enchantment active, switching to a spear (Melee, Piercing) would not apply the Culling enchantment which requires a Melee, Slashing weapon.

If you still think there is a bug please provide the specific steps needed to reproduce it.
