### ISSUE TITLE
[Feature] One Feat Per Level Compatibility/Integration

### ISSUE THREAD

**Issue by BellaRoka** [WittleWolfie/AutomaticBonusProgression#13]
Hi there, love the mod!

I was wondering if it would be possible to merge this mod with the [One Feat Per Level mod](https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/160) or add compatibility for it. I know that what that mod offers isn't necessarily within the scope of this one, but it seems that due to how they both change the default character table they are incompatible currently.

Thanks!

**Comment by WittleWolfie** [comment]
I don't have access to the source of that mod directly but it looks like they are overwriting the feat progression rather than just adding to it.

Try this version and let me know if it works; if so I'll include this in the next release.

[AutomaticBonusProgression.zip](https://github.com/WittleWolfie/AutomaticBonusProgression/files/12566248/AutomaticBonusProgression.zip)

**Comment by BellaRoka** [comment]
Didn't seem to do anything sadly. With only the .zip you gave me, TTCore, ModMenu, and Toybox installed I booted it up and tried making a new character but nothing seems to have changed.

**Comment by WittleWolfie** [comment]
This worked for me locally, try it.

[AutomaticBonusProgression.zip](https://github.com/WittleWolfie/AutomaticBonusProgression/files/12566398/AutomaticBonusProgression.zip)

**Comment by BellaRoka** [comment]
Hmm, still didn't do anything for me.

**Comment by BellaRoka** [comment]
Okay I think I may have possibly misunderstood what you did. I had thought you had added the One Feat Per Level mod's functionality into AutoBonusProgression as a standalone feature so I was testing the zip you gave me without One Feat installed. On a whim I decided to reinstall the One Feat mod with the zip you gave me and that made everything work just fine. So I'm guessing you'd just added a compatibility feature?

**Comment by WittleWolfie** [comment]
Yes I added compatibility.

**Comment by BellaRoka** [comment]
Ahhh okay awesome, in that case it works perfectly. Sorry for the earlier confusion!
Thanks a bunch for taking the time to help me out!

**Comment by WittleWolfie** [comment]
Glad it works!
