### ISSUE TITLE
[Feature] Extend weapon enhancement to natural attacks beyond the first 2.

### ISSUE THREAD

**Issue by FrijDom** [WittleWolfie/AutomaticBonusProgression#14]
For example, say I have a half-orc Shifter with the Razortusk feat. I have two claws and a bite. If I full-attack, my claws get their enhancement bonuses (and any abilities from my Legendary Gifts), but my bite gets nothing at all.

I'd like to request either an option or just a basic addition that either extends the bonuses from weapon enhancement to natural attacks after the first two, or to allow Amulets of Mighty Fists to apply to those.

As it stands, there is no way with this mod to get an enhancement bonus on your further natural attacks, which nerfs shifters (especially the Manticore shifter) in a way that's just unnecessary. It also nerfs barbarian and monk natural attackers, as well as bloodragers (though that one I don't mind so much.)

**Comment by WittleWolfie** [comment]
They should be applying. What level are you? Your bite should be a secondary attack so it'll get the secondary / off-hand progression.

**Comment by FrijDom** [comment]
When I initially noticed it, I was playing a Manticore Shifter, and all my attacks were primary; When I went into Manticore shape, I got an extra 2 spike attacks, and neither of those got the enhancement.

**Comment by WittleWolfie** [comment]
What level were you? You wouldn't get a bonus until level 8.

If you still think there's an issue please share your logs: https://github.com/WittleWolfie/AutomaticBonusProgression#reporting-problems
