### ISSUE TITLE
Feature Request: Legendary Gifts

### ISSUE THREAD

**Issue by Kithys** [WittleWolfie/AutomaticBonusProgression#15]
Is it possible to add the option to disable the Legendary Gifts that come from mythic ranks? I was hoping to be able to use just the ABP without all of the extra power that comes from the extra Legendary Gifts.

**Comment by WittleWolfie** [comment]
Yeah I can do that. I'll plan for this weekend.

**Comment by Kithys** [comment]
Thanks! Of course you should leave the ones in that are part of the ABP in PF1, just the Mythic ones should be optional :)

You're the best!

**Comment by WittleWolfie** [comment]
Fixed in the next release.
