### ISSUE TITLE
Mental Prowess does not qualify for Feat prerequisites

### ISSUE THREAD

**Issue by RomaInvictus** [WittleWolfie/AutomaticBonusProgression#16]
Expected behavior: Mental Prowess functions as the Headband of Intellect it replaces and qualifies animal companions for more feats
Actual behavior: animal companions still cannot take feats that require 3 int unless an ASI is applied

**Comment by WittleWolfie** [comment]
This is an unfortunate consequence of the way the game is coded. While this is technically fixable it's a difficult fix that's at high risk of introducing bugs.

I'd suggest using a mod such as ToyBox to bypass requirements if you want this.
