### ISSUE TITLE
Spirit Hunter's Spirit Enchantment does not function until level 4

### ISSUE THREAD

**Issue by RomaInvictus** [WittleWolfie/AutomaticBonusProgression#17]
Expected behaviour: Spirit Enchantment increases weapon enhancement bonus by 1 in all cases
Actual behaviour: Spirit Enchantment only increases weapon enhancement bonus if the weapon already has a bonus from being at least level 4

**Comment by WittleWolfie** [comment]
Thanks for the report! I have an idea what's going on. I haven't been actively developing but I'm planning to return when the next DLC drops and fix any outsanding issues.

**Comment by WittleWolfie** [comment]
A note to myself: to fix this I need to grant WeaponAttunement at level 1. I think the calculator is already correct so it should be safe to just apply.
