### ISSUE TITLE
Not really sure what happened, used the legendary weapon ability on ulbrig in gryphon form.

### ISSUE THREAD

**Issue by Lilith-Daemon** [WittleWolfie/AutomaticBonusProgression#7]
![image](https://github.com/WittleWolfie/AutomaticBonusProgression/assets/116676336/002f2de8-e223-4781-9111-52602ddd2921)
[Player.log](https://github.com/WittleWolfie/AutomaticBonusProgression/files/12270037/Player.log)

The game log full is too big for github, so sent it to you via DM

**Comment by WittleWolfie** [comment]
Thanks! Received `GameLogFull.txt` by DM on Discord.

Most likely this is an issue w/ Shapeshifters so I should take a look. Also fix that uncentered text 🤔
